# 1.

In [ ]:
documents = ['The cat and dog sat on the mat.',
             'The stock market reached an all-time high today.',
             'The dog barked at the stranger in the park.',
             'Crytocurrency has become a popular investment option in recent years.',
             'Apples and oranges are both healthy fruit options.']
label = ['Animal','Finance','Animal','Finance','Food']

from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer(stop_words = 'english',
                               ngram_range=(1,2))
count_vector.fit(documents)
count_vector.vocabulary_


{'cat': 4,
 'dog': 8,
 'sat': 34,
 'mat': 21,
 'cat dog': 5,
 'dog sat': 10,
 'sat mat': 35,
 'stock': 36,
 'market': 19,
 'reached': 30,
 'time': 40,
 'high': 15,
 'today': 42,
 'stock market': 37,
 'market reached': 20,
 'reached time': 31,
 'time high': 41,
 'high today': 16,
 'barked': 2,
 'stranger': 38,
 'park': 27,
 'dog barked': 9,
 'barked stranger': 3,
 'stranger park': 39,
 'crytocurrency': 6,
 'popular': 28,
 'investment': 17,
 'option': 22,
 'recent': 32,
 'years': 43,
 'crytocurrency popular': 7,
 'popular investment': 29,
 'investment option': 18,
 'option recent': 23,
 'recent years': 33,
 'apples': 0,
 'oranges': 25,
 'healthy': 13,
 'fruit': 11,
 'options': 24,
 'apples oranges': 1,
 'oranges healthy': 26,
 'healthy fruit': 14,
 'fruit options': 12}


# 2.

In [ ]:
terms = count_vector.get_feature_names_out()
doc_array = count_vector.transform(documents).toarray()
doc_lenth = doc_array.sum(axis=1)
tf_mat = doc_array / doc_lenth.reshape(-1,1)
word = count_vector.vocabulary_
print(tf_mat)
print(tf_mat[2][word.get('dog')])
print(terms)
print(doc_array.shape)
print(documents[2] ,"->", doc_array[2][8])


[[0.         0.         0.         0.         0.14285714 0.14285714
  0.         0.         0.14285714 0.         0.14285714 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.14285714 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.14285714 0.14285714
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.09090909 0.09090909 0.
  0.         0.09090909 0.09090909 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.09090909 0.09090909 0.         0.         0.         0.
  0.09090909 0.09090909 0.         0.         0.09090909 0.09090909
  0.09090909 0.        ]
 [0.         0.         0.14285714 0.14285714 0.         0.
  0.         0.         0.


# 3.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
softmax = LogisticRegression()
softmax.fit(doc_array,label)
pre = softmax.predict_proba(doc_array)
print(pre)
print(softmax.classes_)
# print(accuracy_score(pre,label))

[[0.85123481 0.09152153 0.05724366]
 [0.09103509 0.85897216 0.04999275]
 [0.85123481 0.09152153 0.05724366]
 [0.09103509 0.85897216 0.04999275]
 [0.11550163 0.09877078 0.78572759]]
['Animal' 'Finance' 'Food']


# 4.

In [ ]:
from re import A
from sklearn.naive_bayes import CategoricalNB
doc_ver1 = ['fruit options']
doc_ver1 = count_vector.transform(doc_ver1).toarray()
clf = CategoricalNB()
clf.fit(doc_array,label)
y_label = clf.predict(doc_array)
A,F,Fo = clf.predict_proba(doc_ver1)[0]
print("proba A ",A)
print("proba F ",F)
print("proba Fo ",Fo)
print(y_label)

proba A  0.6609471520680834
proba F  0.03438550443111914
proba Fo  0.304667343500799
['Animal' 'Finance' 'Animal' 'Finance' 'Food']


In [ ]:
from sklearn.metrics import classification_report
target_names=['Animal' 'Finance' 'Food']
print(classification_report(label,y_label))

              precision    recall  f1-score   support

      Animal       1.00      1.00      1.00         2
     Finance       1.00      1.00      1.00         2
        Food       1.00      1.00      1.00         1

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5



# 5.

In [ ]:
import numpy as np
import subprocess
! curl https://raw.githubusercontent.com/PyThaiNLP/thai-sentiment-analysis-dataset/master/review_shopping.csv > file.txt
document2 = subprocess.getoutput("cut -d'\t' -f1 < file.txt")
document2 = document2.split("\n")
label2 = subprocess.getoutput("cut -d'\t' -f2 < file.txt")
label2 = label2.split("\n")
len(label2)
label2.count('neg')
# print(document2)
# print(label2)

# document2 = [x.replace(' ', '') for x in document2]
document2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19211  100 19211    0     0  36277      0 --:--:-- --:--:-- --:--:-- 36247


['เกลียด ชอบหลอกให้สั่งซื้อ ที่ไหนได้ไม่มีสิ้นค้า',
 'สินค้าด้อยคุณภาพ',
 'สินค้าหมดทำไมไม่แจ้งขึ้นว่าหมดอะ.กดใส่ตะกร้าไปเถอะ.เซ็งเรย',
 'อย่าทำแบบนี้กับใครอีกนะค่ะแย่มากค่ะ',
 'คือเเบบผิดหวังมาก เเย่ที่สุดได้ของมาฝาเเตก เเตกนิดหน่อยไม่ว่าเเตกเยอะมาก ครั้งเดียวพอจบเเยก😢',
 'ส่งช้าจัง รอนานมาก ยกเลิกก้อไม่ได้',
 'แย่มากกกกกกค่ะ เอาของพังมาให้ฉุนมาดค่ะไม่พอใจเป็นอย่างมากค่ะ. ส่งของ ก็ไม่ได้ใบเสร็จ. ไม่ไหวจะเคลียร์',
 'ไม่แนะนำซื้อมาใช้ได้วันเดียวใช้ไม่ได้แล้ว',
 'แย่ๆสั่งสินค้าไปหลายวันแล้วไม่ส่งให้สักทีเหนื่อยกับการรอคอย',
 'เสียความรู้สึกอย่างมาก สวยแต่ในรูปใส่ได้ครั้งเดียว ไม่ดี',
 'ยอดเยี่ยมค่ะ ราคาเหมาะสม บอกต่อได้เลยค่ะ',
 'สวยค่ะ เหมือนในรูปเลย ชอบค่ะ ส่งของไวมากก',
 'ใช้ดีค่ะหน้านุ่มและขาวขึ้น',
 'จัดส่งเร็วมาก สะดวกดี ของจริงขนาดใหญ่กว่าที่คิดไว้ แต่ใช้งานได้ดี',
 'ชอบสินค้ามาก ไม่ผิดหวังที่รอ สวยยังบรรจุภัณฑ์คับ',
 'สินค้าส่งรวดเร็ว พอใจในสินค้าครับ',
 'สินค้าคุณภาพดี แข็งแรง เสียงดี เด็กๆ ชอบ และยังส่งเร็วด้วยค่ะ',
 'ราคากับคุณภาพของสินค้ามีความเหมาะสม ใช้งานง่าย',
 'ส่งของไว 

# 6.

In [ ]:
! pip install PyThaiNLP
from pythainlp.corpus.common import thai_stopwords
from pythainlp import  word_tokenize
from pythainlp.util import normalize
thai = list(thai_stopwords())
def text_process(text):
  prunct =  [',','?','.',';',':','!','ๆ','ฯ']
  clean = [x for x in text if x not in prunct]
  clean = ''.join(clean)
  clean = word_tokenize(clean)
  clean = [normalize(x) for x in clean]
  final = [x for x in clean if x not in thai]
  final = ''.join(final)
  return final
  # return word_tokenize(text)


text_process_value = text_process(document2)
# text_process_value = [text_process(doc) for doc in document2]
print(text_process_value)


เกลียดชอบหลอกสั่งซื้อที่ไหนได้ค้าสินค้าด้อยคุณภาพสินค้าแจ้งอะ.กดใส่ตะกร้า.เซ็งเรยอย่าทำแบบนี้แย่มากผิดหวังแย่ฝาเเตกเเตกเเตกจบเเยก😢รอยกเลิกก้อแย่กกกกกกพังฉุนมาดพอใจเป็นอย่างมาก.ใบเสร็จ.ไหวจะเคลียร์แนะนำซื้อใช้ได้ใช้ไม่ได้แย่สั่งสินค้าสักทีเหนื่อยการรอคอยเสียความรู้สึกสวยรูปใส่ดียอดเยี่ยมราคาเหมาะสมบอกต่อสวยเหมือนรูปชอบไวกกดีหน้านุ่มขาวจัดส่งสะดวกดีของจริงขนาดใหญ่ใช้งานได้ดีชอบสินค้าผิดหวังรอสวยบรรจุภัณฑ์คับสินค้าส่งพอใจสินค้าสินค้าคุณภาพดีแข็งแรงเสียงดีเด็กชอบราคาคุณภาพสินค้าความเหมาะสมใช้งานไวห่อพัสดุดีใช้งานเยี่ยมสวยการจัดส่งดีเดือนพังแย่เสียใจความรู้สึกกระเป๋ากะสินค้าแพ็คแย่ถุงดำใส่ขยะแถมสกปรกตรวจสอบมือลูกค้าซื้อฟรีปรับปรุงด่วน!!!!แย่มากขนาดตะโกนรอเดี๋ยวโยนสินค้าข้ามรั้วโน้ตบุคเสียหายทำรถระบบพังผิดหวังลบหมดอายุขายเสียใจผิดหวังแพงตอนนี้ผิดหวังดีสินค้าคุณภาพสายกางเกงๆรอจนรำคาญคุณภาพคุ้มค่าดีดีคุ้มราคาสินค้าสินค้าคุณภาพสวมใส่ตัวๆๆก..แถมสินค้าต้องการสวยรับประทานดีมองเห็นความเปลี่ยนแปลงร่างกายทานรู้สึกดีได้ดีเหมาะกับราคาสรุปดีสินค้าใช้แล้วดีมากลูกแพ้แถมราคาห้างร้านค้าใช้งานดีมากไวสั่งตอนเ

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words=thai,
                             tokenizer=text_process,
                             ngram_range=(1,2),
                             min_df=2)
vectorizer.fit(document2)
vectorizer.vocabulary_
terms = vectorizer.get_feature_names_out()
doc_array2 = vectorizer.transform(document2).toarray()


print(doc_array2.shape)
print(doc_array2)
print(terms)
print(len(vectorizer.vocabulary_))
print(vectorizer.vocabulary_)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:406: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ก', 'ง', 'จ', 'ช', 'ด', 'ต', 'ถ', 'ท', 'น', 'บ', 'ป', 'พ', 'ม', 'ย', 'ร', 'ล', 'ว', 'ส', 'ห', 'อ', 'ะ', 'ั', 'า', 'ำ', 'ิ', 'ี', 'ึ', 'ื', 'ู', 'เ', 'แ', 'โ', 'ใ', 'ไ', '็', '่', '้', '๋', '์', '\ufeff'] not in stop_words.
  warnings.warn(


(128, 510)
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.0776411  0.         0.14753657]
 [0.         0.         0.         ... 0.         0.         0.        ]]
['k' 'o' 'o k' 'ก' 'ก ก' 'ก ข' 'ก ค' 'ก ง' 'ก ซ' 'ก ด' 'ก ต' 'ก น' 'ก พ'
 'ก ร' 'ก ล' 'ก ว' 'ก ส' 'ก ห' 'ก อ' 'ก ะ' 'ก ั' 'ก า' 'ก ำ' 'ก เ' 'ก แ'
 'ก โ' 'ก ใ' 'ก ๊' 'ข' 'ข น' 'ข อ' 'ข า' 'ข ็' 'ข ้' 'ค' 'ค ด' 'ค ร' 'ค ล'
 'ค ว' 'ค ส' 'ค อ' 'ค ะ' 'ค ั' 'ค า' 'ค ื' 'ค ุ' 'ค เ' 'ค ่' 'ค ้' 'ฆ'
 'ฆ ษ' 'ง' 'ง ก' 'ง ค' 'ง จ' 'ง ฉ' 'ง ช' 'ง ซ' 'ง ด' 'ง ต' 'ง ท' 'ง ป'
 'ง พ' 'ง ย' 'ง ร' 'ง ล' 'ง ส' 'ง ห' 'ง า' 'ง ิ' 'ง เ' 'ง แ' 'ง ใ' 'จ'
 'จ ด' 'จ น' 'จ บ' 'จ ร' 'จ ส' 'จ อ' 'จ ะ' 'จ ั' 'จ ุ' 'จ ้' 'ฉ' 'ช' 'ช อ'
 'ช ั' 'ช ้' 'ซ' 'ซ ื' 'ซ ็' 'ญ' 'ญ 

# 7.

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(document2,label2,test_size=0.2)
# print(X_train.shape,X_test.shape)
print(f"Training set size: {len(X_train)}")
print(f"Test set size: {len(X_test)}")
print(X_test)
X_train = vectorizer.transform(X_train).toarray()
X_test = vectorizer.transform(X_test).toarray()
print(len(X_train[0]))

Training set size: 102
Test set size: 26
['รายการไม่ดี ที่จับไม่ดีและสั้น', 'ส่งของไว ห่อพัสดุดี  ของใช้งานเยี่ยม', 'ถูกกว่าในห้างเยอะเลยครับ ภาพชัด สินค้าใหม่ พนักงานบริการดีมาก สั่งสินค้ากับลาซาด้าไม่เคยผิดหวังเลยครับ', 'เสียงดี ส่งเร็ว ราคานี้คุ้มครับ ', 'เห็นแล้วรู้สึกแย่ ไม่มั่นใจในสินค้าร้านนี้', 'สินค้าไม่มีคุณภาพสายกางเกงไม่เท่ากัน', 'ผ้านิ่ม เด้งๆ ดีกว่าที่คิดไว้ ชอบคะ', 'ส่งของไวมาก แต่ราคาขึ้นลงบ่อยมา ต้องเข้ามาเช็คราคาบ่อยๆ ว่าวันไหนจะราคาถูก แต่คุ้มแน่นอนค่ะ เลือกซื้ออันนี้ไม่ผิดหวังค่ะ', 'สินค้าใช้ดีสีสดใช้จนถึงทุกวันนี้', 'แย่มากเลย นมใกล้หมดอายุ ครั้งนี้ครั้งสุดท้ายนะคะที่จะสั่ง', 'สมราคาค่ะ ภาพชัดเจน เทียบกับยี่ห้ออื่นราคาถูกกว่า', 'ซื้อมายังไม่ทันเล่นเลยพังซะแล้ว', 'วัสดุค่อนข้างดีนับว่าคุ้มราคาครับ', 'รับประทานดีอยู่นะครับ มองเห็นความเปลี่ยนแปลงของร่างกาย ทานแล้วรู้สึกว่าดีนะ', 'เนื้อผ้าดีมากๆๆๆๆเกินราคา กำลังจะสั่งเพิ่มอีก ช้าหน่อยแต่ได้มาไม่ผิดหวังเลยค่ะ', 'สวยค่ะ เหมือนในรูปเลย ชอบค่ะ ส่งของไวมากก', 'ได้รับสินค้าเร็วค่ะ และสินค้าก็มีคุณภาพ สวมใส่สบายตัวมากๆๆ เลยค่

In [ ]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import accuracy_score
clf = CategoricalNB()
clf.fit(X_train,y_train)
y_label = clf.predict(X_test)
accuracy = accuracy_score(y_label, y_test)
print(accuracy)
print(y_label)

0.6153846153846154
['neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg'
 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg' 'neg'
 'neg' 'neg']


# 8.

In [ ]:
!pip install bpemb
from bpemb import BPEmb
bpemb_th = BPEmb(lang="th")
# bpemb_th.encode("โชคดีจริง")
def bpemb_tokenizer(text):
  prunct =  [',','?','.',';',':','!','ๆ','ฯ']
  clean = [x for x in text if x not in prunct]
  clean = ''.join(clean)

  clean = [normalize(x) for x in clean]
  clean = ''.join(clean)
  return bpemb_th.encode(clean)

vectorizerBPE = TfidfVectorizer(stop_words=thai,
                             tokenizer=bpemb_tokenizer,)
                            #  ngram_range=(1,2),
                            #  min_df=2)
vectorizerBPE.fit(document2)
vectorizerBPE.vocabulary_
terms = vectorizerBPE.get_feature_names_out()
doc_arrayBPE = vectorizerBPE.transform(document2).toarray()
print(doc_arrayBPE.shape)
print(doc_arrayBPE)
print(terms)
print(len(vectorizerBPE.vocabulary_))
print(vectorizerBPE.vocabulary_)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:406: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ก', 'กบ', 'กระ', 'กระท', 'กล', 'กวน', 'กอน', 'กอบ', 'กาล', 'ข', 'ขน', 'ขา', 'ค', 'คณ', 'คน', 'คร', 'คอ', 'คอย', 'ง', 'งบ', 'งาน', 'จ', 'ฉ', 'ฉะ', 'ช', 'ชน', 'ชนก', 'ชา', 'ซ', 'ญ', 'ฏ', 'ด', 'ดก', 'ดง', 'ดน', 'ดอย', 'ต', 'ตก', 'ตอ', 'ตอง', 'ถ', 'ถา', 'ท', 'ทน', 'ทาน', 'ทาย', 'น', 'นก', 'นน', 'นอน', 'นา', 'บ', 'บาย', 'ป', 'ปวง', 'ผ', 'ผม', 'ฝ', 'พ', 'พาะ', 'ม', 'มง', 'มน', 'มวล', 'มอ', 'มาจาก', 'มาย', 'ย', 'ยง', 'ยน', 'ยะ', 'ยายาม', 'ร', 'รก', 'รง', 'รณ', 'รด', 'รบ', 'รม', 'รอง', 'ระ', 'ระยะเวลา', 'ล', 'ลา', 'ลาย', 'ว', 'วก', 'วง', 'วด', 'วน', 'วบ', 'วย', 'วา', 'วาง', 'วาน', 'ศก', 'สง', 'สด', 'สน', 'สบ', 'สม

(128, 378)
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.15827222 ... 0.         0.         0.        ]
 [0.17468144 0.         0.0760336  ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
['00' 'ok' 'ก' 'กด' 'กบ' 'กร' 'กรด' 'กระ' 'กรา' 'กล' 'กลอง' 'กว' 'กวน'
 'กอ' 'กอง' 'กอน' 'กอบ' 'กะ' 'กาง' 'กาย' 'การทํางาน' 'กําหนด' 'ข' 'ขน'
 'ขนาด' 'ขา' 'ขาม' 'ขาย' 'ขาว' 'ค' 'คณ' 'คน' 'คบ' 'คม' 'คร' 'คล' 'คอ'
 'คอน' 'คอม' 'คอย' 'คะแนน' 'คา' 'คาด' 'คาท' 'คาน' 'คาม' 'คาร' 'คาส' 'ง'
 'งาน' 'จ' 'จบ' 'จอ' 'จะทํา' 'ฉ' 'ฉก' 'ช' 'ชด' 'ชน' 'ชอบ' 'ชา' 'ซ' 'ซอ'
 'ซอง' 'ซา' 'ญ' 'ณฑ' 'ด' 'ดง' 'ดน' 'ดม' 'ดร' 'ดอย' 'ดา' 'ดํา' 'ต' 'ตก'
 'ตร' 'ตรวจสอบ' 'ตลาด' 'ตอ' 'ตอง' 'ตอน' 'ตะ' 'ตํา' 'ถ' 'ถา' 'ถาม' 'ท' 'ทน'
 'ทบ' 'ทร' 'ทะ' 'ทาน' 'ธ' 'น' 'นก' 'นคร' 'น

# 9.

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(document2,label2,test_size=0.2)
# print(X_train.shape,X_test.shape)
print(f"Training set size: {len(X_train)}")
print(f"Test set size: {len(X_test)}")
print(X_test)
X_train = vectorizerBPE.transform(X_train).toarray()
X_test = vectorizerBPE.transform(X_test).toarray()
print(len(X_train[0]))
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score
clf1 = BernoulliNB()
clf1.fit(X_train,y_train)
y_label = clf1.predict(X_test)
accuracy = accuracy_score(y_label, y_test)
print(accuracy)
print(y_label)
print(clf1.classes_)

Training set size: 102
Test set size: 26
['รายการไม่ดี ที่จับไม่ดีและสั้น', 'ผ้านิ่ม เด้งๆ ดีกว่าที่คิดไว้ ชอบคะ', 'แย่มากเลย นมใกล้หมดอายุ ครั้งนี้ครั้งสุดท้ายนะคะที่จะสั่ง', 'สินค้าคุณภาพดี แข็งแรง เสียงดี เด็กๆ ชอบ และยังส่งเร็วด้วยค่ะ', 'อย่าขายเลย ยกเลิกโปรนี้เถอะ เสียความรู้สึก ดูมาหลายเดือนละ', 'เสียความรู้สึกค่ะมาไม่ตรงที่สั่ง', 'ใช้เดือนเดียวพังแย่ๆมากๆ', 'ใช้ดียังไม่มีปัญหาอะไรค่ะชอบมาก', 'ใช้ดีส่งของไว มากเจ้านี้  วัสดุคุณภาพจริงจริง', 'ได้รับของเร็วมาก กระทะร้อนเร็ว ทำอาหารได้หลายอย่างเลยค่ะ ชอบมาก', 'สมราคาค่ะ ภาพชัดเจน เทียบกับยี่ห้ออื่นราคาถูกกว่า', 'เสียความรู้สึกอย่างมาก สวยแต่ในรูปใส่ได้ครั้งเดียว ไม่ดี', 'ผิดหวัง ลบไม่ออก', 'สวยมาใช้งานง่ายมากที่สำคัญส่งเร็วมาก', 'แย่มาก บิดน้ำไม่แห้ง เสียดายตังมาก', 'สินค้ามีตำหนิ แย่มากๆ ไม่ไหวๆเลย ถ้ามีตำหนิก็บอกด้วยครับ จะได้ทำใจก่อนซื้อ', 'สินค้าแพคอย่างดี ที่สำคัญส่งขอเร็วมาก คิดว่าจะได้ช้าเสียอีก', 'สเป็คถือว่าโอเครเลยคับ ไหลลื่นดีไม่มีสดุด สมกับราคา และคุ้มค่ามากๆเลย', 'วัสดุค่อนข้างดีนับว่าคุ้มราคาครับ', 'คือเเบบผิดหวังมาก เ

# 10.

In [ ]:
test_doc = ['สินค้าตรงปกส่งไว','ไม่ไหวอย่างแรงไร้สาระ']
test_doc = vectorizerBPE.transform(test_doc).toarray()
negative,positive = clf1.predict_proba(test_doc)[0]
print(negative)
print(positive)
print(clf1.predict_proba(test_doc))


0.07726960263357859
0.9227303973664206
[[0.0772696  0.9227304 ]
 [0.97167621 0.02832379]]
